In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn import metrics

X, y = np.arange(10).reshape((5, 2)), range(5)
print(f"x = \n{X}")
print(f"y = {y}")

x = 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y = range(0, 5)


In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [40]:
print(X_train)

[[4 5]
 [0 1]
 [6 7]]


In [41]:
print(y_train)

[2, 0, 3]


In [42]:
print(X_test)

[[2 3]
 [8 9]]


In [43]:
print(y_test)

[1, 4]


In [48]:
clf = MLPClassifier(hidden_layer_sizes=(10, 8), random_state=1, max_iter=10000000).fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)
print(y_test)
print(y_pred)

Accuracy:  0.0
[1, 4]
[0 3]
